env:
  es2021: true
  node: true
extends:
  - standard
  - eslint:recommended
  - plugin:prettier/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
rules: 
  import/no-named-default: 0

